# Generated by Django 4.0.3 on 2022-03-27 02:36

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_payment_property_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=300)),
                ('phone_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('Party Paid', 'Party Paid')], max_length=200)),
                ('agreement_id', models.CharField(max_length=200)),
                ('agreement_date', models.DateField()),
            ],
        ),
    ]
