# Generated by Django 4.0.3 on 2022-03-27 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='project_name',
            field=models.CharField(default='My Project', max_length=200),
        ),
        migrations.AddField(
            model_name='agreement',
            name='property_name',
            field=models.CharField(default='My Property', max_length=200),
        ),
    ]
