# Generated by Django 3.2.8 on 2022-03-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0005_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_no',
            field=models.BigIntegerField(unique=True),
        ),
    ]
