# Generated by Django 4.0.3 on 2022-03-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0006_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('Residential', 'Residential'), ('Flat', 'Flat'), ('Commercial', 'Commercial'), ('Bunglow', 'Bunglow')], max_length=200)),
                ('sub_property', models.CharField(max_length=200)),
            ],
        ),
    ]
