# Generated by Django 3.2.8 on 2022-03-30 19:09

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0006_alter_client_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
