# Generated by Django 4.0.3 on 2022-03-27 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0007_property_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property_type',
            old_name='property_type',
            new_name='properties_type',
        ),
    ]
