# Generated by Django 4.0.3 on 2022-03-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0008_rename_property_type_property_type_properties_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property_type',
            old_name='properties_type',
            new_name='properties',
        ),
        migrations.AlterField(
            model_name='property_type',
            name='sub_property',
            field=models.CharField(default='Company', max_length=200),
        ),
    ]
