# Generated by Django 4.0.3 on 2022-03-31 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0007_alter_client_phone_no'),
        ('baseapp', '0010_amenities'),
    ]

    operations = [
    ]
