# Generated by Django 4.0.3 on 2022-03-31 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0011_merge_0007_alter_client_phone_no_0010_amenities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Telecaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('qualification', models.CharField(choices=[('12thPass', '12thPass'), ('b.b.a', 'b.b.a'), ('b.s.c', 'b.s.c'), ('M.B.A', 'M.B.A'), ('B.COM', 'B.COM')], max_length=200)),
                ('experience', models.IntegerField(default=0)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('pin', models.IntegerField(default=0)),
            ],
        ),
    ]
