# Generated by Django 4.0.3 on 2022-04-13 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0013_add_salesperson_alter_add_telecaller_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewLead_Telecaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=200, unique=True)),
                ('dob', models.DateField()),
                ('interested_property', models.CharField(choices=[('Villa', 'Villa'), ('1 BHK', '1 BHK'), ('2 BHK', '2 BHK'), ('3 BHK', '3 BHK'), ('Commercial', 'Commercial')], max_length=200)),
                ('budget', models.IntegerField(default=0)),
                ('next_followup', models.DateField()),
            ],
        ),
    ]
