# Generated by Django 4.0.3 on 2022-04-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0014_newlead_telecaller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=200, unique=True)),
                ('project_type', models.CharField(max_length=300)),
                ('property_type', models.CharField(choices=[('Villa', 'Villa'), ('1 BHK', '1 BHK'), ('2 BHK', '2 BHK'), ('3 BHK', '3 BHK'), ('Commercial', 'Commercial')], max_length=200)),
                ('salesperson', models.IntegerField(default=0)),
                ('amount', models.CharField(max_length=300)),
            ],
        ),
    ]
